stages:
  - test
default:
  image: registry.gitlab.com/etke.cc/base/build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /root/cache/

test:
  stage: test
  script:
    - just lint
    - just test
